name: Fixer

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write # for stefanzweifel/git-auto-commit-action to push code in repo
    name: Style code fixer

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Composer
        run: composer install

      - name: Style code fixer
        run: composer format

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Style code
